services:
  - type: web
    name: jennyblog
    env: node
    buildCommand: yarn install && yarn build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 10000 