services:
  - type: web
    name: jennyblog
    env: static
    buildCommand: yarn install && yarn build && cp public/_redirects dist/
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      # SPA fallback - serve index.html for all non-file routes
      - type: rewrite
        source: /*
        destination: /index.html 